export const REQUEST_STATUS_LABELS: Record<string, string> = {
  DRAFT: 'Draft',
  QUOTE_CALCULATED: 'Quote Calculated',
  PENDING_CUSTOMER_REVIEW: 'Pending Review',
  ACCEPTED_BY_CUSTOMER: 'Accepted',
  INVOICE_GENERATED: 'Invoice Generated',
  AWAITING_COD_PAYMENT: 'Awaiting Payment',
  PAYMENT_RECEIVED: 'Payment Received',
  CREDIT_APPROVED_FOR_REQUEST: 'Credit Approved',
  IN_PROGRESS: 'In Progress',
  PENDING_CUSTOMER_ACTION: 'Action Required',
  CLOSED: 'Closed',
  CANCELLED: 'Cancelled',
  ON_HOLD: 'On Hold',
};

export const SUB_REQUEST_STATUS_LABELS: Record<string, string> = {
  PICKUP_REQUESTED: 'Pickup Requested',
  WAYBILL_AVAILABLE: 'Waybill Available',
  PICKUP_SCHEDULED: 'Pickup Scheduled',
  AWAITING_COLLECTION: 'Awaiting Collection',
  SAMPLE_COLLECTED: 'Sample Collected',
  IN_TRANSIT_TO_LAB: 'In Transit',
  DELIVERED_TO_LAB: 'Delivered to Lab',
  SAMPLE_ACCEPTED_BY_LAB: 'Sample Accepted',
  SAMPLE_EXCEPTION_LOGGED: 'Exception Logged',
  TESTING_SCHEDULED: 'Testing Scheduled',
  TESTING_IN_PROGRESS: 'Testing In Progress',
  TESTING_DELAYED: 'Testing Delayed',
  TESTING_COMPLETED: 'Testing Completed',
  AWAITING_GOLAB_REVIEW: 'Awaiting Review',
  RETURNED_TO_LAB: 'Returned to Lab',
  ON_HOLD_WITH_GOLAB: 'On Hold',
  APPROVED_FOR_RELEASE: 'Approved',
  RELEASED_TO_CUSTOMER: 'Released',
  LAB_ALLOCATION_EXCEPTION: 'Allocation Exception',
  PICKUP_EXCEPTION: 'Pickup Exception',
  SAMPLE_REJECTED: 'Sample Rejected',
};

export const STATUS_COLORS: Record<string, string> = {
  DRAFT: 'gray',
  QUOTE_CALCULATED: 'blue',
  PENDING_CUSTOMER_REVIEW: 'yellow',
  ACCEPTED_BY_CUSTOMER: 'green',
  INVOICE_GENERATED: 'blue',
  AWAITING_COD_PAYMENT: 'orange',
  PAYMENT_RECEIVED: 'green',
  CREDIT_APPROVED_FOR_REQUEST: 'green',
  IN_PROGRESS: 'blue',
  PENDING_CUSTOMER_ACTION: 'yellow',
  CLOSED: 'gray',
  CANCELLED: 'red',
  ON_HOLD: 'orange',
  PICKUP_REQUESTED: 'blue',
  WAYBILL_AVAILABLE: 'blue',
  PICKUP_SCHEDULED: 'blue',
  AWAITING_COLLECTION: 'yellow',
  SAMPLE_COLLECTED: 'green',
  IN_TRANSIT_TO_LAB: 'blue',
  DELIVERED_TO_LAB: 'green',
  SAMPLE_ACCEPTED_BY_LAB: 'green',
  SAMPLE_EXCEPTION_LOGGED: 'red',
  TESTING_SCHEDULED: 'blue',
  TESTING_IN_PROGRESS: 'blue',
  TESTING_DELAYED: 'orange',
  TESTING_COMPLETED: 'green',
  AWAITING_GOLAB_REVIEW: 'yellow',
  RETURNED_TO_LAB: 'orange',
  ON_HOLD_WITH_GOLAB: 'orange',
  APPROVED_FOR_RELEASE: 'green',
  RELEASED_TO_CUSTOMER: 'green',
  LAB_ALLOCATION_EXCEPTION: 'red',
  PICKUP_EXCEPTION: 'red',
  SAMPLE_REJECTED: 'red',
};

export const TEST_CATEGORIES = [
  'Water',
  'Soil',
  'Food',
  'Materials',
  'Environmental',
  'Chemical',
] as const;

export type TestCategory = (typeof TEST_CATEGORIES)[number];
