export { renderRequestForm } from './templates/request-form';
export type { RequestFormData, RequestFormSubRequest, RequestFormTest } from './templates/request-form';
export { renderQuote } from './templates/quote';
export type { QuoteData, QuoteLineItem } from './templates/quote';
export { renderInvoice } from './templates/invoice';
export type { InvoiceData, InvoiceLineItem } from './templates/invoice';
export { renderWaybill } from './templates/waybill';
export type { WaybillData, WaybillAddress } from './templates/waybill';
export { renderCertificate } from './templates/certificate';
export type { CertificateData, CertificateTestResult } from './templates/certificate';
export { BASE_STYLES, wrapInDocument, escapeHtml, formatCurrency, formatDate, golabHeader, golabFooter } from './styles';
