import { wrapInDocument, escapeHtml, formatDate, golabHeader, golabFooter } from '../styles';

export interface CertificateTestResult { testName: string; testCode: string; result: string; unit?: string; method?: string; toleranceMin?: number | string | null; toleranceMax?: number | string | null; toleranceUnit?: string | null; pass?: boolean | null; }
export interface CertificateData { certificateNumber: string; date: Date | string; subReference: string; requestReference: string; format: 'LAB_ORIGINAL' | 'GOLAB_BRANDED'; laboratory: { name: string; code: string; accreditation?: string }; customer: { name: string; contactName: string }; sampleInfo?: { description?: string; receivedDate?: Date | string; testedDate?: Date | string; condition?: string }; testResults: CertificateTestResult[]; reviewedBy?: string | null; reviewedAt?: Date | string | null; notes?: string | null; }

export function renderCertificate(data: CertificateData): string {
  const branded = data.format === 'GOLAB_BRANDED';
  const title = '<div style="text-align: center; margin-bottom: 20px;"><h2 style="font-size: 16pt; color: #1e40af;">Certificate of Analysis</h2><p style="font-size: 10pt; color: #6b7280;">' + escapeHtml(data.certificateNumber) + ' - ' + escapeHtml(data.subReference) + '</p></div>';
  const parties = '<div class="section"><div class="info-grid"><div><div class="section-title">Customer</div><strong>' + escapeHtml(data.customer.name) + '</strong><br>' + escapeHtml(data.customer.contactName) + '<br>Request: ' + escapeHtml(data.requestReference) + '</div><div><div class="section-title">Laboratory</div><strong>' + escapeHtml(data.laboratory.name) + '</strong><br>Code: ' + escapeHtml(data.laboratory.code) + '</div></div></div>';
  const rows = data.testResults.map(r => '<tr><td>' + escapeHtml(r.testName) + '</td><td>' + escapeHtml(r.testCode) + '</td><td>' + (r.method ? escapeHtml(r.method) : '-') + '</td><td class="text-right">' + escapeHtml(r.result) + (r.unit ? ' ' + escapeHtml(r.unit) : '') + '</td><td class="text-center">' + (r.pass == null ? '-' : r.pass ? '<span class="badge badge-green">PASS</span>' : '<span class="badge badge-red">FAIL</span>') + '</td></tr>').join('');
  const results = '<div class="section"><div class="section-title">Test Results</div><table><thead><tr><th>Test</th><th>Code</th><th>Method</th><th class="text-right">Result</th><th class="text-center">Status</th></tr></thead><tbody>' + rows + '</tbody></table></div>';
  const seal = branded ? '<div class="certificate-seal"><div style="font-size: 24pt;">&#9733;</div><div style="font-weight: 600; color: #1e40af;">GoLab Verified</div></div>' : '';
  const sig = '<div class="signature-block"><div class="signature-line">Laboratory Signatory</div>' + (branded && data.reviewedBy ? '<div class="signature-line">GoLab Reviewer: ' + escapeHtml(data.reviewedBy) + '</div>' : '') + '</div>';
  return wrapInDocument('Certificate - ' + data.certificateNumber, golabHeader('Certificate of Analysis', data.certificateNumber, data.date) + '<div class="certificate-border">' + title + parties + results + (data.notes ? '<div class="section"><div class="section-title">Notes</div><p>' + escapeHtml(data.notes) + '</p></div>' : '') + seal + sig + '</div>' + golabFooter());
}
